export const MOCK_VIDEO_DATA = [
  {
    title: "u don't cook in which house 🤪🤪🤪",
    author: "markangelcomedy",
    platform: "TikTok",
    thumbnail: "https://picsum.photos/seed/video1/1080/1920",
    duration: 6,
    best_filesize_bytes: 762570,
    worst_filesize_bytes: 172573,
    audio_filesize_bytes: 98450,
    video_link: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    audio_link: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    images: false,
  },
  {
    title: "When you try your best but you fail miserably 😂",
    author: "funnyvibes_daily",
    platform: "Instagram",
    thumbnail: "https://picsum.photos/seed/video2/1080/1920",
    duration: 15,
    best_filesize_bytes: 1845200,
    worst_filesize_bytes: 420100,
    audio_filesize_bytes: 245100,
    video_link: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    audio_link: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    images: false,
  },
  {
    title: "Top 5 quick tech lifehacks for 2026 🚀",
    author: "tech_reflexx",
    platform: "Facebook",
    thumbnail: "https://picsum.photos/seed/video3/1080/1920",
    duration: 30,
    best_filesize_bytes: 4520100,
    worst_filesize_bytes: 980500,
    audio_filesize_bytes: null,
    video_link: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    audio_link: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    images: false,
  },
];