import {
  HiOutlineDownload,
  HiOutlineAdjustments,
  HiOutlineCode,
  HiOutlineDocumentText,
  HiOutlineColorSwatch,
  HiOutlineDatabase,
  HiOutlineKey,
  HiOutlinePhotograph,
  HiOutlineQrcode,
  HiOutlineScissors,
  HiOutlineUser,
  HiOutlineTerminal,
  HiOutlineVariable,
} from "react-icons/hi";

// Add new tools directly to this array
// Set `hot: true` to prioritize tools at the top of the grid

export const TOOLS = [
  {
    id: "social-downloader",
    name: "Social Media Downloader",
    description: "Extract and download videos or audio from supported social platforms.",
    category: "Media",
    href: "/social-media-downloader",
    icon: HiOutlineDownload,
    hot: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Create strong, customizable cryptographically secure passwords.",
    category: "Security",
    href: "/password-generator",
    icon: HiOutlineKey,
    hot: true,
  },
  {
    id: "qr-and-barcode-generator",
    name: "QR and Barcode Reader & Generator",
    description: "Generate downloadable QR codes for links, text, and WiFi networks.",
    category: "Utility",
    href: "/qr-and-barcode-tool",
    icon: HiOutlineQrcode,
    hot: true,
  },
  {
    id: "image-optimizer",
    name: "Image Optimizer",
    description: "Compress and convert images into web-ready formats.",
    category: "Media",
    href: "/optimizer",
    icon: HiOutlineAdjustments,
    hot: false,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Validate, format, and minify JSON data structures.",
    category: "Developer",
    href: "/formatter",
    icon: HiOutlineCode,
    hot: true,
  },
  {
    id: "text-converter",
    name: "Text Case Converter",
    description: "Transform text between camelCase, snake_case, slug, and more.",
    category: "Text",
    href: "/converter",
    icon: HiOutlineDocumentText,
    hot: false,
  },
  {
    id: "color-palette",
    name: "Color Palette Picker",
    description: "Extract color palettes from images or generate custom HEX/RGB codes.",
    category: "Design",
    href: "/color-palette",
    icon: HiOutlineColorSwatch,
    hot: false,
  },
  {
    id: "svg-encoder",
    name: "SVG Encoder & Cleaner",
    description: "Optimize raw SVG code, remove metadata, and encode to Data URI.",
    category: "Developer",
    href: "/svg-encoder",
    icon: HiOutlinePhotograph,
    hot: false,
  },
  {
    id: "markdown-preview",
    name: "Markdown Editor",
    description: "Write and preview styled Markdown content with live HTML export.",
    category: "Text",
    href: "/markdown",
    icon: HiOutlineTerminal,
    hot: false,
  },
  {
    id: "fake-name-generator",
    name: "Fake Name Generator",
    description: "Generate realistic fake profiles, names, addresses, and random user credentials.",
    category: "Utility",
    href: "/fake-name-generator",
    icon: HiOutlineUser,
    hot: true,
  },
  {
    id: "bg-remover",
    name: "Background Remover",
    description: "Isolate subjects and strip backgrounds from photos automatically.",
    category: "Media",
    href: "/bg-remover",
    icon: HiOutlineScissors,
    hot: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Calculate MD5, SHA-1, SHA-256, and SHA-512 string hashes.",
    category: "Security",
    href: "/hash-generator",
    icon: HiOutlineDatabase,
    hot: false,
  },
  {
    id: "base64-converter",
    name: "Base64 Encoder",
    description: "Encode or decode strings and files to and from Base64 format.",
    category: "Developer",
    href: "/base64",
    icon: HiOutlineVariable,
    hot: false,
  },
  {
    id: "pdf-merger",
    name: "PDF Merger",
    description: "Combine multiple PDF documents into a single organized file.",
    category: "Utility",
    href: "/pdf-merger",
    icon: HiOutlineDocumentText,
    hot: false,
  },
];